import type { Metadata } from "next";

import FindYourSchool from "./page";

export const metadata: Metadata = {
  title: "Find Your School | CampusConnect",
  description: "Generated by create next app",
};

export default FindYourSchool;
