import "@/app/globals.css";

import type { Metadata } from "next";
import Script from "next/script";
import { Montserrat, Open_Sans, Work_Sans } from "next/font/google";
import localFont from "next/font/local";
import React from "react";

import { SuperTokensProvider } from "@/components/SupertokensProvider";
import { ThemeProvider } from "@/components/theme-provider";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const futura = localFont({
  src: [
    {
      path: "../public/fonts/Futura Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-futura",
});

export const metadata: Metadata = {
  title: "CampusConnect",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "CampusConnect",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${workSans.className} ${montserrat.variable} ${futura.variable}`}
      >
        <ThemeProvider>
          <SuperTokensProvider>{children}</SuperTokensProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
